site_name:Exakat Documentation
site_url:http://www.exakat.io/
repo_url:http://www.github.com/exakat/exakat
site_description:Exakat Engine Documentation
site_author:Damien Seguy
site_favicon: favicon.ico
copyright:Exakat ltd, 2013-2015
pages:
- 'Manual': 'manual.md'
- 'Rules': 'Rules.md'